export const TABLE_PRODUCTS = process.env.NEXT_PUBLIC_TABLE_PRODUCTS;
export const TABLE_CONSULTS = process.env.NEXT_PUBLIC_TABLE_CONSULTS;
export const MP_ACCESS_TOKEN = process.env.NEXT_PUBLIC_MP_ACCES_TOKEN;
